# Generated by Django 4.2.23 on 2025-10-02 19:05

import apps.models.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Model Adı')),
                ('original_file', models.FileField(upload_to=apps.models.models.upload_to_original, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['stl', 'ply'])], verbose_name='Model Dosyası')),
                ('file_format', models.CharField(max_length=10, verbose_name='Dosya Formatı')),
                ('file_size', models.BigIntegerField(verbose_name='Dosya Boyutu (bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False, verbose_name='İşlendi mi?')),
            ],
            options={
                'verbose_name': '3D Model',
                'verbose_name_plural': '3D Modeller',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Proje Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('processing', 'İşleniyor'), ('completed', 'Tamamlandı')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_type', models.CharField(choices=[('rotation', 'Döndürme'), ('cutting', 'Kesme'), ('fill_holes', 'Delik Doldurma'), ('smoothing', 'Yumuşatma'), ('ovalization', 'Ovalleştirme'), ('bulging', 'Bombeleştirme'), ('drilling', 'Delik Delme')], max_length=20, verbose_name='İşlem Tipi')),
                ('parameters', models.JSONField(verbose_name='Parametreler')),
                ('result_file', models.FileField(upload_to=apps.models.models.upload_to_processed, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['stl', 'ply'])], verbose_name='Sonuç Dosyası')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution_time', models.FloatField(verbose_name='Çalışma Süresi (saniye)')),
                ('success', models.BooleanField(default=True, verbose_name='Başarılı mı?')),
                ('error_message', models.TextField(blank=True, verbose_name='Hata Mesajı')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_steps', to='models.model3d')),
            ],
            options={
                'verbose_name': 'İşleme Adımı',
                'verbose_name_plural': 'İşleme Adımları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('processed_file', models.FileField(upload_to=apps.models.models.upload_to_exports, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['stl', 'ply'])], verbose_name='İşlenmiş Dosya')),
                ('final_vertices_count', models.IntegerField(verbose_name='Final Vertex Sayısı')),
                ('final_faces_count', models.IntegerField(verbose_name='Final Face Sayısı')),
                ('quality_score', models.FloatField(blank=True, null=True, verbose_name='Kalite Skoru')),
                ('is_printable', models.BooleanField(default=False, verbose_name='Basılabilir mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_versions', to='models.model3d')),
                ('processing_steps', models.ManyToManyField(to='models.processingstep', verbose_name='İşleme Adımları')),
            ],
            options={
                'verbose_name': 'İşlenmiş Model',
                'verbose_name_plural': 'İşlenmiş Modeller',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vertices_count', models.IntegerField(verbose_name='Vertex Sayısı')),
                ('faces_count', models.IntegerField(verbose_name='Face Sayısı')),
                ('is_watertight', models.BooleanField(default=False, verbose_name='Kapalı mı?')),
                ('volume', models.FloatField(blank=True, null=True, verbose_name='Hacim (mm³)')),
                ('surface_area', models.FloatField(blank=True, null=True, verbose_name='Yüzey Alanı (mm²)')),
                ('bounding_box_min', models.JSONField(verbose_name='Bounding Box Min')),
                ('bounding_box_max', models.JSONField(verbose_name='Bounding Box Max')),
                ('top_points', models.JSONField(verbose_name='Üst Noktalar')),
                ('bottom_points', models.JSONField(verbose_name='Alt Noktalar')),
                ('sharp_points', models.JSONField(verbose_name='Sivri Noktalar')),
                ('widest_area', models.JSONField(verbose_name='En Geniş Alan')),
                ('narrowest_area', models.JSONField(verbose_name='En Dar Alan')),
                ('topology_status', models.CharField(choices=[('good', 'İyi'), ('has_holes', 'Delikli'), ('non_manifold', 'Manifold Değil'), ('complex', 'Karmaşık')], max_length=20, verbose_name='Topoloji Durumu')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='models.model3d')),
            ],
            options={
                'verbose_name': 'Model Analizi',
                'verbose_name_plural': 'Model Analizleri',
            },
        ),
        migrations.AddField(
            model_name='model3d',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='models.project'),
        ),
    ]
